### ISSUE TITLE
Abandoned ?

### ISSUE THREAD

**Issue by SephVII** [suzaku01/mhfz_questfile_editor#1]
I was wondering if you wanna come back eventually to this project ? Quest Editor seems like a really cool thing to have atleast in my book it sounds fantastic to do this without any manuall hex editing since im totally lost tryin to change Monster stats for example.

**Comment by VictorChan7** [comment]
Can I increase the attack rate, defense multiplier, and hard multiplier of The Monster?

**Comment by suzaku01** [comment]
Strength can be cahnged but you can't chaage it separately.

**Comment by VictorChan7** [comment]
Is the 5th monster impossible to edit? There are only 4 monster items.

**Comment by VictorChan7** [comment]
These （Howling Zinogre,Burning Freezing Eruzerion,Mysterious Mi Ru,Ruler Guanzorumu） monsters don't appear in the editor?

**Comment by suzaku01** [comment]
I am very sorry, but I am unable to provide any support for this project at this time.
